### ISSUE TITLE
CUSTOM_REPOLINT_FILE not respected

### ISSUE THREAD

**Issue by craigez** [philips-labs/github-action-repolinter#2]
Hi,

Thanks for putting this together! Much appreciated.

I don't think the CUSTOM_REPOLINT_FILE environment variable is respected by the underlying repolinter code in the way you are expecting. I tested this here: https://github.com/craigez/license-text-normalizer-js/pull/1

When I don't set CUSTOM_REPOLINT_FILE ENV variable the repolint.json you have included in the action repository is run. When I specify CUSTOM_REPOLINT_FILE, repolinter picks up the default rules set in repolinter installation, not my custom ruleset in my repository. Where you expecting repolinter to do something with the Environment variable?

I was looking at this as part of the Todogroup activities. We are working out the best way path forward to support a GitHub action for repolinter as part of Todogroup activities. We were looking at both your action and the one from newrelic: https://github.com/newrelic/repolinter-action. It seems this is a subset of the newrelic functionality. Though, the docker approach taken here has advantages as the ruby dependencies could be installed (licensee and linguist). (As an aside, if you move the npm install into the Dockerfile I think GitHub Actions will cache the container image and reduce the runtime of the action).

FYI: we are currently reviewing a large PR to repolinter from newrelic: https://github.com/todogroup/repolinter/pull/174

Regards,
Craig

**Comment by JeroenKnoops** [comment]
We like immutable build pipelines, and that's why this github action is created.
I think this should be part of the Todogroup activities, so feel free to be inspired by this code.

If it is available as an official Todogroup action, I will deprecate this action.

Meanwhile I will take a look at the CUSTOM_REPOLINT_FILE parameter.
